# Generated by Django 3.2.3 on 2021-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('BloodGroup', models.CharField(max_length=5)),
                ('City', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('UserId', models.IntegerField()),
            ],
        ),
    ]
