# Generated by Django 3.2.3 on 2021-10-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_details', '0002_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_details',
            name='UserId',
        ),
    ]
