# Generated by Django 3.2.3 on 2021-10-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor_details', '0005_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='Image',
            new_name='Img',
        ),
    ]
